<?php

/**
 * One-off generator for app/Data/world-cup-2026-players.php
 * Run: php scripts/generate-world-cup-players.php
 */
$squads = [
    'south_korea' => ['country' => 'South Korea', 'players' => [
        ['Kim Seung-gyu', 'Goalkeeper', 'FC Tokyo'],
        ['Jo Hyeon-woo', 'Goalkeeper', 'Ulsan HD'],
        ['Song Bum-keun', 'Goalkeeper', 'Jeonbuk Hyundai Motors'],
        ['Kim Min-jae', 'Defender', 'Bayern Munich'],
        ['Kim Moon-hwan', 'Defender', 'Daejeon Hana Citizen'],
        ['Seol Young-woo', 'Defender', 'Red Star Belgrade'],
        ['Cho Yu-min', 'Defender', 'Sharjah'],
        ['Lee Tae-seok', 'Defender', 'Austria Wien'],
        ['Park Jin-seob', 'Defender', 'Zhejiang'],
        ['Kim Tae-hyeon', 'Defender', 'Kashima Antlers'],
        ['Lee Han-beom', 'Defender', 'Midtjylland'],
        ['Jens Castrop', 'Defender', 'Borussia Mönchengladbach'],
        ['Lee Ki-hyuk', 'Defender', 'Gangwon FC'],
        ['Lee Jae-sung', 'Midfielder', 'Mainz'],
        ['Hwang Hee-chang', 'Midfielder', 'Wolves'],
        ['Hwang In-beom', 'Midfielder', 'Feyenoord'],
        ['Lee Kang-in', 'Midfielder', 'PSG'],
        ['Paik Seung-ho', 'Midfielder', 'Birmingham City'],
        ['Kim Jin-gyu', 'Midfielder', 'Jeonbuk Hyundai Motors'],
        ['Lee Dong-gyeong', 'Midfielder', 'Ulsan HD'],
        ['Bae Jun-ho', 'Midfielder', 'Stoke City'],
        ['Eom Ji-sung', 'Midfielder', 'Swansea City'],
        ['Yang Hyun-jun', 'Midfielder', 'Celtic'],
        ['Son Heung-min', 'Forward', 'LAFC'],
        ['Cho Gue-sung', 'Forward', 'Midtjylland'],
        ['Oh Hyeon-gyu', 'Forward', 'Beşiktaş'],
    ]],
    'bosnia_herzegovina' => ['country' => 'Bosnia & Herzegovina', 'players' => [
        ['Nikola Vasilj', 'Goalkeeper', 'St. Pauli'],
        ['Martin Zlomislić', 'Goalkeeper', 'Rijeka'],
        ['Osman Hadžikić', 'Goalkeeper', 'Slaven Belupo'],
        ['Sead Kolašinac', 'Defender', 'Atalanta'],
        ['Dennis Hadžikadunić', 'Defender', 'Sampdoria'],
        ['Amar Dedić', 'Defender', 'Benfica'],
        ['Nikola Katić', 'Defender', 'Schalke'],
        ['Tarik Muharemović', 'Defender', 'Sassuolo'],
        ['Nihad Mujakić', 'Defender', 'Gaziantep'],
        ['Stjepan Radeljić', 'Defender', 'Rijeka'],
        ['Nidal Čelik', 'Defender', 'Lens'],
        ['Amir Hadžiahmetović', 'Midfielder', 'Hull City'],
        ['Benjamin Tahirović', 'Midfielder', 'Brøndby'],
        ['Armin Gigović', 'Midfielder', 'Young Boys'],
        ['Dženis Burnić', 'Midfielder', 'Karlsruher SC'],
        ['Ivan Bašić', 'Midfielder', 'Astana'],
        ['Esmir Bajraktarević', 'Midfielder', 'PSV Eindhoven'],
        ['Amar Memić', 'Midfielder', 'Viktoria Plzeň'],
        ['Ivan Šunjić', 'Midfielder', 'Pafos'],
        ['Kerim Alajbegović', 'Midfielder', 'RB Salzburg'],
        ['Ermin Mahmić', 'Midfielder', 'Slovan Liberec'],
        ['Edin Džeko', 'Forward', 'Schalke'],
        ['Ermedin Demirović', 'Forward', 'Stuttgart'],
        ['Samed Baždar', 'Forward', 'Jagiellonia Białystok'],
        ['Haris Tabaković', 'Forward', 'Borussia Mönchengladbach'],
        ['Jovo Lukić', 'Forward', 'Universitatea Cluj'],
    ]],
    'switzerland' => ['country' => 'Switzerland', 'players' => [
        ['Gregor Kobel', 'Goalkeeper', 'Borussia Dortmund'],
        ['Yvon Mvogo', 'Goalkeeper', 'Lorient'],
        ['Marvin Keller', 'Goalkeeper', 'Young Boys'],
        ['Ricardo Rodriguez', 'Defender', 'Real Betis'],
        ['Manuel Akanji', 'Defender', 'Inter'],
        ['Nico Elvedi', 'Defender', 'Borussia Mönchengladbach'],
        ['Silvan Widmer', 'Defender', 'Mainz'],
        ['Eray Cömert', 'Defender', 'Valencia'],
        ['Miro Muheim', 'Defender', 'Hamburg'],
        ['Aurèle Amenda', 'Defender', 'Eintracht Frankfurt'],
        ['Luca Jaquez', 'Defender', 'Stuttgart'],
        ['Granit Xhaka', 'Midfielder', 'Sunderland'],
        ['Remo Freuler', 'Midfielder', 'Bologna'],
        ['Denis Zakaria', 'Midfielder', 'Monaco'],
        ['Djibril Sow', 'Midfielder', 'Sevilla'],
        ['Michel Aebischer', 'Midfielder', 'Pisa'],
        ['Fabian Rieder', 'Midfielder', 'Augsburg'],
        ['Christian Fassnacht', 'Midfielder', 'Young Boys'],
        ['Johan Manzambi', 'Midfielder', 'Freiburg'],
        ['Ardon Jashari', 'Midfielder', 'Milan'],
        ['Breel Embolo', 'Forward', 'Rennes'],
        ['Rubén Vargas', 'Forward', 'Sevilla'],
        ['Dan Ndoye', 'Forward', 'Nottingham Forest'],
        ['Zeki Amdouni', 'Forward', 'Burnley'],
        ['Noah Okafor', 'Forward', 'Leeds United'],
        ['Cedric Itten', 'Forward', 'Fortuna Düsseldorf'],
    ]],
    'brazil' => ['country' => 'Brazil', 'players' => [
        ['Alisson', 'Goalkeeper', 'Liverpool'],
        ['Ederson', 'Goalkeeper', 'Fenerbahçe'],
        ['Weverton', 'Goalkeeper', 'Grêmio'],
        ['Marquinhos', 'Defender', 'PSG'],
        ['Danilo Luiz', 'Defender', 'Flamengo'],
        ['Alex Sandro', 'Defender', 'Flamengo'],
        ['Gabriel Magalhães', 'Defender', 'Arsenal'],
        ['Bremer', 'Defender', 'Juventus'],
        ['Wesley', 'Defender', 'Roma'],
        ['Roger Ibañez', 'Defender', 'Al Ahli'],
        ['Douglas Santos', 'Defender', 'Zenit'],
        ['Léo Pereira', 'Defender', 'Flamengo'],
        ['Casemiro', 'Midfielder', 'Manchester United'],
        ['Lucas Paquetá', 'Midfielder', 'Flamengo'],
        ['Bruno Guimarães', 'Midfielder', 'Newcastle'],
        ['Fabinho', 'Midfielder', 'Al Ittihad'],
        ['Danilo Santos', 'Midfielder', 'Botafogo'],
        ['Neymar', 'Forward', 'Santos'],
        ['Vinicius Junior', 'Forward', 'Real Madrid'],
        ['Raphinha', 'Forward', 'Barcelona'],
        ['Gabriel Martinelli', 'Forward', 'Arsenal'],
        ['Matheus Cunha', 'Forward', 'Manchester United'],
        ['Endrick', 'Forward', 'Lyon'],
        ['Luiz Henrique', 'Forward', 'Zenit'],
        ['Igor Thiago', 'Forward', 'Brentford'],
        ['Rayan', 'Forward', 'Bournemouth'],
    ]],
    'haiti' => ['country' => 'Haiti', 'players' => [
        ['Johny Placide', 'Goalkeeper', 'Bastia'],
        ['Alexandre Pierre', 'Goalkeeper', 'Sochaux'],
        ['Josué Duverger', 'Goalkeeper', 'Cosmos Koblenz'],
        ['Ricardo Adé', 'Defender', 'LDU Quito'],
        ['Carlens Arcus', 'Defender', 'Angers'],
        ['Martin Expérience', 'Defender', 'Nancy'],
        ['Jean-Kévin Duverne', 'Defender', 'Gent'],
        ['Duke Lacroix', 'Defender', 'Colorado Springs Switchbacks FC'],
        ['Wilguens Paugain', 'Defender', 'Zulte Waregem'],
        ['Hannes Delcroix', 'Defender', 'Lugano'],
        ['Keeto Thermoncy', 'Defender', 'Young Boys'],
        ['Leverton Pierre', 'Midfielder', 'Vizela'],
        ['Danley Jean Jacques', 'Midfielder', 'Philadelphia Union'],
        ['Carl Sainté', 'Midfielder', ''],
        ['Jean‐Ricner Bellegarde', 'Midfielder', 'Wolves'],
        ['Woodensky Pierre', 'Midfielder', 'El Paso Locomotive FC'],
        ['Dominique Simon', 'Midfielder', 'Tatran Prešov'],
        ['Duckens Nazon', 'Forward', 'Esteghal'],
        ['Frantzdy Pierrot', 'Forward', 'Çaykur Rizespor'],
        ['Derrick Etienne Jr.', 'Forward', 'Toronto FC'],
        ['Louicius Deedson', 'Forward', 'FC Dallas'],
        ['Ruben Providence', 'Forward', 'Almere City'],
        ['Josué Casimir', 'Forward', 'Auxerre'],
        ['Yassin Fortuné', 'Forward', 'Vizela'],
        ['Wilson Isidor', 'Forward', 'Sunderland'],
        ['Lenny Joseph', 'Forward', 'Ferencváros'],
    ]],
    'scotland' => ['country' => 'Scotland', 'players' => [
        ['Craig Gordon', 'Goalkeeper', 'Hearts'],
        ['Angus Gunn', 'Goalkeeper', 'Nottingham Forest'],
        ['Liam Kelly', 'Goalkeeper', 'Rangers'],
        ['Andy Robertson', 'Defender', 'Liverpool'],
        ['Grant Hanley', 'Defender', 'Hibernian'],
        ['Kieran Tierney', 'Defender', 'Celtic'],
        ['Scott McKenna', 'Defender', 'Dinamo Zagreb'],
        ['Jack Hendry', 'Defender', 'Al Ettifaq'],
        ['Nathan Patterson', 'Defender', 'Everton'],
        ['Anthony Ralston', 'Defender', 'Celtic'],
        ['John Souttar', 'Defender', 'Rangers'],
        ['Aaron Hickey', 'Defender', 'Brentford'],
        ['Dominic Hyam', 'Defender', 'Wrexham'],
        ['John McGinn', 'Midfielder', 'Aston Villa'],
        ['Scott McTominay', 'Midfielder', 'Napoli'],
        ['Ryan Christie', 'Midfielder', 'Bournemouth'],
        ['Kenny McLean', 'Midfielder', 'Norwich City'],
        ['Billy Gilmour', 'Midfielder', 'Napoli'],
        ['Lewis Ferguson', 'Midfielder', 'Bologna'],
        ['Ben Gannon-Doak', 'Midfielder', 'Bournemouth'],
        ['Findlay Curtis', 'Midfielder', 'Kilmarnock'],
        ['Lyndon Dykes', 'Forward', 'Charlton Athletic'],
        ['Ché Adams', 'Forward', 'Torino'],
        ['Lawrence Shankland', 'Forward', 'Hearts'],
        ['George Hirst', 'Forward', 'Ipswich Town'],
        ['Ross Stewart', 'Forward', 'Southampton'],
    ]],
    'germany' => ['country' => 'Germany', 'players' => [
        ['Manuel Neuer', 'Goalkeeper', 'Bayern Munich'],
        ['Oliver Baumann', 'Goalkeeper', 'Hoffenheim'],
        ['Alexander Nübel', 'Goalkeeper', 'Stuttgart'],
        ['Antonio Rüdiger', 'Defender', 'Real Madrid'],
        ['Jonathan Tah', 'Defender', 'Bayern Munich'],
        ['David Raum', 'Defender', 'RB Leipzig'],
        ['Nico Schlotterbeck', 'Defender', 'Borussia Dortmund'],
        ['Waldemar Anton', 'Defender', 'Borussia Dortmund'],
        ['Malick Thiaw', 'Defender', 'Newcastle United'],
        ['Nathaniel Brown', 'Defender', 'Eintracht Frankfurt'],
        ['Joshua Kimmich', 'Midfielder', 'Bayern Munich'],
        ['Leroy Sané', 'Midfielder', 'Galatasaray'],
        ['Leon Goretzka', 'Midfielder', 'Bayern Munich'],
        ['Kai Havertz', 'Midfielder', 'Arsenal'],
        ['Jamal Musiala', 'Midfielder', 'Bayern Munich'],
        ['Florian Wirtz', 'Midfielder', 'Liverpool'],
        ['Pascal Groß', 'Midfielder', 'Brighton & Hove Albion'],
        ['Nadiem Amiri', 'Midfielder', 'Mainz'],
        ['Aleksandar Pavlović', 'Midfielder', 'Bayern Munich'],
        ['Angelo Stiller', 'Midfielder', 'Stuttgart'],
        ['Felix Nmecha', 'Midfielder', 'Borussia Dortmund'],
        ['Jamie Leweling', 'Midfielder', 'Stuttgart'],
        ['Lennart Karl', 'Midfielder', 'Bayern Munich'],
        ['Nick Woltemade', 'Forward', 'Newcastle United'],
        ['Deniz Undav', 'Forward', 'Stuttgart'],
        ['Maximilian Beier', 'Forward', 'Borussia Dortmund'],
    ]],
    'curacao' => ['country' => 'Curaçao', 'players' => [
        ['Eloy Room', 'Goalkeeper', 'Miami FC'],
        ['Trevor Doornbusch', 'Goalkeeper', 'VVV-Venlo'],
        ['Tyrick Bodak', 'Goalkeeper', 'Telstar'],
        ['Juriën Gaari', 'Defender', 'Abha'],
        ['Roshon van Eijma', 'Defender', 'RKC Waalwijk'],
        ['Sherel Floranus', 'Defender', 'PEC Zwolle'],
        ['Joshua Brenet', 'Defender', 'Kayserispor'],
        ['Shurandy Sambo', 'Defender', 'Sparta Rotterdam'],
        ['Armando Obispo', 'Defender', 'PSV Eindhoven'],
        ['Riechedly Bazoer', 'Defender', 'Konyaspor'],
        ['Deveron Fonville', 'Defender', 'NEC Nijmegen'],
        ['Leandro Bacuna', 'Midfielder', 'Iğdir F.K.'],
        ['Juninho Bacuna', 'Midfielder', 'Volendam'],
        ['Godfried Roemeratoe', 'Midfielder', 'RKC Waalwijk'],
        ['Kevin Felida', 'Midfielder', 'Den Bosch'],
        ['Livano Comenencia', 'Midfielder', 'Zürich'],
        ['Ar\'jany Martha', 'Midfielder', 'Rotherham United'],
        ['Tyrese Noslin', 'Midfielder', 'Telstar'],
        ['Kenji Gorré', 'Forward', 'Maccabi Haifa'],
        ['Brandley Kuwas', 'Forward', 'Volendam'],
        ['Gervane Kastaneer', 'Forward', 'Terengganu'],
        ['Jeremy Antonisse', 'Forward', 'A.E. Kifisia'],
        ['Jearl Margaritha', 'Forward', 'SK Beveren'],
        ['Jürgen Locadia', 'Forward', 'Miami FC'],
        ['Sontje Hansen', 'Forward', 'Middlesbrough'],
        ['Tahith Chong', 'Forward', 'Sheffield United'],
    ]],
    'ivory_coast' => ['country' => 'Ivory Coast', 'players' => [
        ['Yahia Fofana', 'Goalkeeper', 'Çaykur Rizespor'],
        ['Alban Lafont', 'Goalkeeper', 'Panathinaikos'],
        ['Mohamed Koné', 'Goalkeeper', 'Charleroi'],
        ['Ghislain Konan', 'Defender', 'Gil Vicente'],
        ['Odilon Kossounou', 'Defender', 'Atalanta'],
        ['Wilfried Singo', 'Defender', 'Galatasaray'],
        ['Evan Ndicka', 'Defender', 'Roma'],
        ['Emmanuel Agbadou', 'Defender', 'Beşiktaş'],
        ['Guéla Doué', 'Defender', 'Strasbourg'],
        ['Ousmane Diomande', 'Defender', 'Sporting CP'],
        ['Clément Akpa', 'Defender', 'Auxerre'],
        ['Franck Kessié', 'Midfielder', 'Al Ahli'],
        ['Jean Michaël Seri', 'Midfielder', 'Maribor'],
        ['Ibrahim Sangaré', 'Midfielder', 'Nottingham Forest'],
        ['Seko Fofana', 'Midfielder', 'Porto'],
        ['Christ Inao Oulaï', 'Midfielder', 'Trabzonspor'],
        ['Parfait Guiagon', 'Midfielder', 'Charleroi'],
        ['Nicolas Pépé', 'Forward', 'Villarreal'],
        ['Oumar Diakité', 'Forward', 'Cercle Brugge'],
        ['Simon Adingra', 'Forward', 'Monaco'],
        ['Evann Guessand', 'Forward', 'Crystal Palace'],
        ['Amad Diallo', 'Forward', 'Manchester United'],
        ['Yan Diomande', 'Forward', 'RB Leipzig'],
        ['Bazoumana Touré', 'Forward', 'Hoffenheim'],
        ['Elye Wahi', 'Forward', 'Nice'],
        ['Ange-Yoan Bonny', 'Forward', 'Inter Milan'],
    ]],
    'japan' => ['country' => 'Japan', 'players' => [
        ['Zion Suzuki', 'Goalkeeper', 'Parma'],
        ['Keisuke Ōsako', 'Goalkeeper', 'Sanfrecce Hiroshima'],
        ['Tomoki Hayakawa', 'Goalkeeper', 'Kashima Antlers'],
        ['Yūto Nagatomo', 'Defender', 'FC Tokyo'],
        ['Takehiro Tomiyasu', 'Defender', 'Ajax'],
        ['Ko Itakura', 'Defender', 'Ajax'],
        ['Shōgo Taniguchi', 'Defender', 'Sint-Truiden'],
        ['Hiroki Ito', 'Defender', 'Bayern Munich'],
        ['Yukinari Sugawara', 'Defender', 'Werder Bremen'],
        ['Ayumu Seko', 'Defender', 'Le Havre'],
        ['Tsuyoshi Watanabe', 'Defender', 'Feyenoord'],
        ['Junnosuke Suzuki', 'Defender', 'Copenhagen'],
        ['Wataru Endo', 'Midfielder', 'Liverpool'],
        ['Junya Itō', 'Midfielder', 'Genk'],
        ['Ritsu Dōan', 'Midfielder', 'Eintracht Frankfurt'],
        ['Daichi Kamada', 'Midfielder', 'Crystal Palace'],
        ['Takefusa Kubo', 'Midfielder', 'Real Sociedad'],
        ['Ao Tanaka', 'Midfielder', 'Leeds United'],
        ['Keito Nakamura', 'Midfielder', 'Reims'],
        ['Kaishu Sano', 'Midfielder', 'Mainz'],
        ['Ayase Ueda', 'Forward', 'Feyenoord'],
        ['Daizen Maeda', 'Forward', 'Celtic'],
        ['Kōki Ogawa', 'Forward', 'NEC'],
        ['Yuito Suzuki', 'Forward', 'Freiburg'],
        ['Keisuke Gotō', 'Forward', 'Sint-Truiden'],
        ['Kento Shiogai', 'Forward', 'Wolfsburg'],
    ]],
    'sweden' => ['country' => 'Sweden', 'players' => [
        ['Kristoffer Nordfeldt', 'Goalkeeper', 'AIK'],
        ['Viktor Johansson', 'Goalkeeper', 'Stoke City'],
        ['Jacob Widell Zetterström', 'Goalkeeper', 'Derby County'],
        ['Victor Lindelöf', 'Defender', 'Aston Villa'],
        ['Isak Hien', 'Defender', 'Atalanta'],
        ['Gabriel Gudmundsson', 'Defender', 'Leeds United'],
        ['Carl Starfelt', 'Defender', 'Celta Vigo'],
        ['Emil Holm', 'Defender', 'Juventus'],
        ['Hjalmar Ekdal', 'Defender', 'Burnley'],
        ['Daniel Svensson', 'Defender', 'Borussia Dortmund'],
        ['Gustaf Lagerbielke', 'Defender', 'Braga'],
        ['Eric Smith', 'Defender', 'St. Pauli'],
        ['Elliot Stroud', 'Defender', 'Mjällby AIF'],
        ['Mattias Svanberg', 'Midfielder', 'Wolfsburg'],
        ['Jesper Karlström', 'Midfielder', 'Udinese'],
        ['Yasin Ayari', 'Midfielder', 'Brighton & Hove Albion'],
        ['Lucas Bergvall', 'Midfielder', 'Tottenham Hotspur'],
        ['Besfort Zeneli', 'Midfielder', 'Union Saint-Gilloise'],
        ['Alexander Isak', 'Forward', 'Liverpool'],
        ['Viktor Gyökeres', 'Forward', 'Arsenal'],
        ['Ken Sema', 'Forward', 'Pafos'],
        ['Anthony Elanga', 'Forward', 'Newcastle United'],
        ['Benjamin Nygren', 'Forward', 'Celtic'],
        ['Alexander Bernhardsson', 'Forward', 'Holstein Kiel'],
        ['Gustaf Nilsson', 'Forward', 'Club Brugge'],
        ['Taha Ali', 'Forward', 'Malmö FF'],
    ]],
    'tunisia' => ['country' => 'Tunisia', 'players' => [
        ['Aymen Dahmen', 'Goalkeeper', 'CS Sfaxien'],
        ['Sabri Ben Hessen', 'Goalkeeper', 'Étoile du Sahel'],
        ['Mouhib Chamakh', 'Goalkeeper', 'Club Africain'],
        ['Montassar Talbi', 'Defender', 'Lorient'],
        ['Dylan Bronn', 'Defender', 'Servette'],
        ['Ali Abdi', 'Defender', 'Nice'],
        ['Yan Valery', 'Defender', 'Young Boys'],
        ['Mohamed Amine Ben Hamida', 'Defender', 'ES Tunis'],
        ['Moutaz Neffati', 'Defender', 'IFK Norrköping'],
        ['Omar Rekik', 'Defender', 'Maribor'],
        ['Adem Arous', 'Defender', 'Kasımpaşa'],
        ['Raed Chikhaoui', 'Defender', 'US Monastir'],
        ['Ellyes Skhiri', 'Midfielder', 'Eintracht Frankfurt'],
        ['Hannibal Mejbri', 'Midfielder', 'Burnley'],
        ['Anis Ben Slimane', 'Midfielder', 'Norwich City'],
        ['Mortadha Ben Ouanes', 'Midfielder', 'Kasımpaşa'],
        ['Ismaël Gharbi', 'Midfielder', 'Augsburg'],
        ['Hadj Mahmoud', 'Midfielder', 'Lugano'],
        ['Rani Khedira', 'Midfielder', 'Union Berlin'],
        ['Elias Achouri', 'Forward', 'Copenhagen'],
        ['Firas Chaouat', 'Forward', 'Club Africain'],
        ['Hazem Mastouri', 'Forward', 'Dynamo Makhachkala'],
        ['Elias Saad', 'Forward', 'Hannover 96'],
        ['Sebastian Tounekti', 'Forward', 'Celtic'],
        ['Khalil Ayari', 'Forward', 'PSG'],
        ['Rayan Elloumi', 'Forward', 'Vancouver Whitecaps'],
    ]],
    'belgium' => ['country' => 'Belgium', 'players' => [
        ['Thibaut Courtois', 'Goalkeeper', 'Real Madrid'],
        ['Senne Lammens', 'Goalkeeper', 'Manchester United'],
        ['Mike Penders', 'Goalkeeper', 'Strasbourg'],
        ['Thomas Meunier', 'Defender', 'Lille'],
        ['Timothy Castagne', 'Defender', 'Fulham'],
        ['Arthur Theate', 'Defender', 'Eintracht Frankfurt'],
        ['Zeno Debast', 'Defender', 'Sporting CP'],
        ['Maxim De Cuyper', 'Defender', 'Brighton & Hove Albion'],
        ['Brandon Mechele', 'Defender', 'Club Brugge'],
        ['Koni De Winter', 'Defender', 'AC Milan'],
        ['Joaquin Seys', 'Defender', 'Club Brugge'],
        ['Nathan Ngoy', 'Defender', 'Lille'],
        ['Axel Witsel', 'Midfielder', 'Girona'],
        ['Kevin De Bruyne', 'Midfielder', 'Napoli'],
        ['Youri Tielemans', 'Midfielder', 'Aston Villa'],
        ['Hans Vanaken', 'Midfielder', 'Club Brugge'],
        ['Amadou Onana', 'Midfielder', 'Aston Villa'],
        ['Nicolas Raskin', 'Midfielder', 'Rangers'],
        ['Romelu Lukaku', 'Forward', 'Napoli'],
        ['Leandro Trossard', 'Forward', 'Arsenal'],
        ['Jérémy Doku', 'Forward', 'Manchester City'],
        ['Dodi Lukébakio', 'Forward', 'Benfica'],
        ['Charles De Ketelaere', 'Forward', 'Atalanta'],
        ['Alexis Saelemaekers', 'Forward', 'Milan'],
        ['Diego Moreira', 'Forward', 'Strasbourg'],
        ['Matias Fernandez-Pardo', 'Forward', 'Lille'],
    ]],
    'new_zealand' => ['country' => 'New Zealand', 'players' => [
        ['Max Crocombe', 'Goalkeeper', 'Millwall'],
        ['Alex Paulsen', 'Goalkeeper', 'Lechia Gdánsk'],
        ['Michael Woud', 'Goalkeeper', 'Auckland FC'],
        ['Tim Payne', 'Defender', 'Wellington Phoenix'],
        ['Francis de Vries', 'Defender', 'Auckland FC'],
        ['Tyler Bindon', 'Defender', 'Sheffield United'],
        ['Michael Boxall', 'Defender', 'Minnesota United'],
        ['Liberato Cacace', 'Defender', 'Wrexham'],
        ['Nando Pijnaker', 'Defender', 'Auckland FC'],
        ['Finn Surman', 'Defender', 'Portland Timbers'],
        ['Callan Elliot', 'Defender', 'Auckland FC'],
        ['Tommy Smith', 'Defender', 'Braintree Town'],
        ['Joe Bell', 'Midfielder', 'Viking'],
        ['Matthew Garbett', 'Midfielder', 'Peterborough United'],
        ['Marko Stamenić', 'Midfielder', 'Swansea City'],
        ['Sarpreet Singh', 'Midfielder', 'Wellington Phoenix'],
        ['Elijah Just', 'Midfielder', 'Motherwell'],
        ['Alex Rufer', 'Midfielder', 'Wellington Phoenix'],
        ['Ben Old', 'Midfielder', 'Saint-Étienne'],
        ['Callum McCowatt', 'Midfielder', 'Silkeborg'],
        ['Ryan Thomas', 'Midfielder', 'PEC Zwolle'],
        ['Lachlan Bayliss', 'Midfielder', 'Newcastle Jets'],
        ['Chris Wood', 'Forward', 'Nottingham Forest'],
        ['Kosta Barbarouses', 'Forward', 'Western Sydney Wanderers'],
        ['Ben Waine', 'Forward', 'Port Vale'],
        ['Jesse Randall', 'Forward', 'Auckland FC'],
    ]],
    'cape_verde' => ['country' => 'Cape Verde', 'players' => [
        ['Vozinha', 'Goalkeeper', 'Chaves'],
        ['Márcio Rosa', 'Goalkeeper', 'Montana'],
        ['CJ dos Santos', 'Goalkeeper', 'San Diego'],
        ['Stopira', 'Defender', 'Torreense'],
        ['Pico', 'Defender', 'Shamrock Rovers'],
        ['João Paulo', 'Defender', 'FCSB'],
        ['Diney', 'Defender', 'Al Bataeh'],
        ['Logan Costa', 'Defender', 'Villarreal'],
        ['Steven Moreira', 'Defender', 'Columbus Crew'],
        ['Wagner Pina', 'Defender', 'Trabzonspor'],
        ['Sidny Lopes Cabral', 'Defender', 'Benfica'],
        ['Kelvin Pires', 'Defender', 'SJK'],
        ['Jamiro Monteiro', 'Midfielder', 'PEC Zwolle'],
        ['Kevin Pina', 'Midfielder', 'Krasnodar'],
        ['Deroy Duarte', 'Midfielder', 'Ludogorets'],
        ['Telmo Arcanjo', 'Midfielder', 'Vitória de Guimarães'],
        ['Laros Duarte', 'Midfielder', 'Puskás Akadémia'],
        ['Yannick Semedo', 'Midfielder', 'Farense'],
        ['Ryan Mendes', 'Forward', 'Iğdır'],
        ['Garry Rodrigues', 'Forward', 'Apollon Limassol'],
        ['Willy Semedo', 'Forward', 'Omonia'],
        ['Jovane Cabral', 'Forward', 'Estrela Amadora'],
        ['Benchimol', 'Forward', 'Akron Tolyatti'],
        ['Dailon Livramento', 'Forward', 'Casa Pia'],
        ['Hélio Varela', 'Forward', 'Maccabi Tel Aviv'],
        ['Nuno da Costa', 'Forward', 'İstanbul Başakşehir'],
    ]],
    'france' => ['country' => 'France', 'players' => [
        ['Mike Maignan', 'Goalkeeper', 'AC Milan'],
        ['Brice Samba', 'Goalkeeper', 'Rennes'],
        ['Robin Risser', 'Goalkeeper', 'Lens'],
        ['Lucas Digne', 'Defender', 'Aston Villa'],
        ['Jules Koundé', 'Defender', 'Barcelona'],
        ['Théo Hernandez', 'Defender', 'Al Hilal'],
        ['Lucas Hernandez', 'Defender', 'PSG'],
        ['Dayot Upamecano', 'Defender', 'Bayern Munich'],
        ['William Saliba', 'Defender', 'Arsenal'],
        ['Ibrahima Konaté', 'Defender', 'Liverpool'],
        ['Malo Gusto', 'Defender', 'Chelsea'],
        ['Maxence Lacroix', 'Defender', 'Crystal Palace'],
        ['N\'Golo Kanté', 'Midfielder', 'Fenerbahçe'],
        ['Adrien Rabiot', 'Midfielder', 'AC Milan'],
        ['Aurélien Tchouaméni', 'Midfielder', 'Real Madrid'],
        ['Manu Koné', 'Midfielder', 'Roma'],
        ['Warren Zaïre-Emery', 'Midfielder', 'PSG'],
        ['Kylian Mbappé', 'Forward', 'Real Madrid'],
        ['Ousmane Dembélé', 'Forward', 'PSG'],
        ['Marcus Thuram', 'Forward', 'Inter Milan'],
        ['Bradley Barcola', 'Forward', 'PSG'],
        ['Michael Olise', 'Forward', 'Bayern Munich'],
        ['Maghnes Akliouche', 'Forward', 'Monaco'],
        ['Désiré Doué', 'Forward', 'PSG'],
        ['Rayan Cherki', 'Forward', 'Manchester City'],
        ['Jean-Philippe Mateta', 'Forward', 'Crystal Palace'],
    ]],
    'norway' => ['country' => 'Norway', 'players' => [
        ['Ørjan Nyland', 'Goalkeeper', 'Sevilla'],
        ['Egil Selvik', 'Goalkeeper', 'Watford'],
        ['Sander Tangvik', 'Goalkeeper', 'Hamburg'],
        ['Kristoffer Ajer', 'Defender', 'Brentford'],
        ['Julian Ryerson', 'Defender', 'Borussia Dortmund'],
        ['Leo Østigård', 'Defender', 'Genoa'],
        ['Marcus Holmgren Pedersen', 'Defender', 'Torino'],
        ['David Møller Wolfe', 'Defender', 'Wolverhampton Wanderers'],
        ['Fredrik André Bjørkan', 'Defender', 'Bodø/Glimt'],
        ['Torbjørn Heggem', 'Defender', 'Bologna'],
        ['Sondre Langås', 'Defender', 'Derby County'],
        ['Henrik Falchener', 'Defender', 'Viking'],
        ['Martin Ødegaard', 'Midfielder', 'Arsenal'],
        ['Sander Berge', 'Midfielder', 'Fulham'],
        ['Patrick Berg', 'Midfielder', 'Bodø/Glimt'],
        ['Kristian Thorstvedt', 'Midfielder', 'Sassuolo'],
        ['Morten Thorsby', 'Midfielder', 'Cremonese'],
        ['Antonio Nusa', 'Midfielder', 'RB Leipzig'],
        ['Fredrik Aursnes', 'Midfielder', 'Benfica'],
        ['Oscar Bobb', 'Midfielder', 'Fulham'],
        ['Jens Petter Hauge', 'Midfielder', 'Bodø/Glimt'],
        ['Andreas Schjelderup', 'Midfielder', 'Benfica'],
        ['Thelo Aasgaard', 'Midfielder', 'Rangers'],
        ['Alexander Sørloth', 'Forward', 'Atlético Madrid'],
        ['Erling Haaland', 'Forward', 'Manchester City'],
        ['Jørgen Strand Larsen', 'Forward', 'Crystal Palace'],
    ]],
    'austria' => ['country' => 'Austria', 'players' => [
        ['Alexander Schlager', 'Goalkeeper', 'RB Salzburg'],
        ['Patrick Pentz', 'Goalkeeper', 'Brøndby'],
        ['Florian Wiegele', 'Goalkeeper', 'Viktoria Plzen'],
        ['David Alaba', 'Defender', 'Real Madrid'],
        ['Stefan Posch', 'Defender', 'Mainz 05'],
        ['Philipp Lienhart', 'Defender', 'Freiburg'],
        ['Kevin Danso', 'Defender', 'Tottenham Hotspur'],
        ['Phillipp Mwene', 'Defender', 'Mainz 05'],
        ['Alexander Prass', 'Defender', 'Hoffenheim'],
        ['Marco Friedl', 'Defender', 'Werder Bremen'],
        ['Michael Svoboda', 'Defender', 'Venezia'],
        ['David Affengruber', 'Defender', 'Elche'],
        ['Marcel Sabitzer', 'Midfielder', 'Borussia Dortmund'],
        ['Christoph Baumgartner', 'Midfielder', 'RB Leipzig'],
        ['Florian Grillitsch', 'Midfielder', 'Braga'],
        ['Konrad Laimer', 'Midfielder', 'Bayern Munich'],
        ['Xaver Schlager', 'Midfielder', 'RB Leipzig'],
        ['Nicolas Seiwald', 'Midfielder', 'RB Leipzig'],
        ['Alessandro Schöpf', 'Midfielder', 'Wolfsberger AC'],
        ['Romano Schmid', 'Midfielder', 'Werder Bremen'],
        ['Patrick Wimmer', 'Midfielder', 'Wolfsburg'],
        ['Carney Chukwuemeka', 'Midfielder', 'Borussia Dortmund'],
        ['Paul Wanner', 'Midfielder', 'PSV Eindhoven'],
        ['Marko Arnautović', 'Forward', 'Red Star Belgrade'],
        ['Michael Gregoritsch', 'Forward', 'Augsburg'],
        ['Saša Kalajdžić', 'Forward', 'LASK'],
    ]],
    'portugal' => ['country' => 'Portugal', 'players' => [
        ['Diogo Costa', 'Goalkeeper', 'Porto'],
        ['José Sá', 'Goalkeeper', 'Wolverhampton Wanderers'],
        ['Rui Silva', 'Goalkeeper', 'Sporting CP'],
        ['Rúben Dias', 'Defender', 'Manchester City'],
        ['João Cancelo', 'Defender', 'Barcelona'],
        ['Nélson Semedo', 'Defender', 'Fenerbahçe'],
        ['Nuno Mendes', 'Defender', 'Paris Saint-Germain'],
        ['Diogo Dalot', 'Defender', 'Manchester United'],
        ['Gonçalo Inácio', 'Defender', 'Sporting CP'],
        ['Matheus Nunes', 'Defender', 'Manchester City'],
        ['Renato Veiga', 'Defender', 'Villarreal'],
        ['Tomás Araújo', 'Defender', 'Benfica'],
        ['Bernardo Silva', 'Midfielder', 'Manchester City'],
        ['Bruno Fernandes', 'Midfielder', 'Manchester United'],
        ['Rúben Neves', 'Midfielder', 'Al Hilal'],
        ['Vitinha', 'Midfielder', 'Paris Saint-Germain'],
        ['João Neves', 'Midfielder', 'Paris Saint-Germain'],
        ['Samú Costa', 'Midfielder', 'Mallorca'],
        ['Cristiano Ronaldo', 'Forward', 'Al Nassr'],
        ['João Félix', 'Forward', 'Al Nassr'],
        ['Rafael Leão', 'Forward', 'Milan'],
        ['Gonçalo Guedes', 'Forward', 'Real Sociedad'],
        ['Gonçalo Ramos', 'Forward', 'Paris Saint-Germain'],
        ['Pedro Neto', 'Forward', 'Chelsea'],
        ['Francisco Trincão', 'Forward', 'Sporting CP'],
        ['Francisco Conceição', 'Forward', 'Juventus'],
    ]],
    'dr_congo' => ['country' => 'DR Congo', 'players' => [
        ['Lionel Mpasi', 'Goalkeeper', 'Le Havre'],
        ['Timothy Fayulu', 'Goalkeeper', 'Noah'],
        ['Matthieu Epolo', 'Goalkeeper', 'Standard Liège'],
        ['Chancel Mbemba', 'Defender', 'Lille'],
        ['Arthur Masuaku', 'Defender', 'Lens'],
        ['Gédéon Kalulu', 'Defender', 'Aris Limassol'],
        ['Joris Kayembe', 'Defender', 'Genk'],
        ['Dylan Batubinsika', 'Defender', 'AEL'],
        ['Axel Tuanzebe', 'Defender', 'Burnley'],
        ['Aaron Wan-Bissaka', 'Defender', 'West Ham United'],
        ['Steve Kapuadi', 'Defender', 'Widzew Łódź'],
        ['Meschak Elia', 'Midfielder', 'Alanyaspor'],
        ['Samuel Moutoussamy', 'Midfielder', 'Atromitos'],
        ['Edo Kayembe', 'Midfielder', 'Watford'],
        ['Charles Pickel', 'Midfielder', 'Espanyol'],
        ['Gaël Kakuta', 'Midfielder', 'AEL'],
        ['Noah Sadiki', 'Midfielder', 'Sunderland'],
        ['Nathanaël Mbuku', 'Midfielder', 'Montpellier'],
        ['Aaron Tshibola', 'Midfielder', 'Kilmarnock'],
        ['Ngal\'ayel Mukau', 'Midfielder', 'Lille'],
        ['Brian Cipenga', 'Midfielder', 'Castellón'],
        ['Cédric Bakambu', 'Forward', 'Real Betis'],
        ['Théo Bongonda', 'Forward', 'Spartak Moscow'],
        ['Fiston Mayele', 'Forward', 'Pyramids'],
        ['Yoane Wissa', 'Forward', 'Newcastle United'],
        ['Simon Banza', 'Forward', 'Al Jazira'],
    ]],
    'england' => ['country' => 'England', 'players' => [
        ['Jordan Pickford', 'Goalkeeper', 'Everton'],
        ['Dean Henderson', 'Goalkeeper', 'Crystal Palace'],
        ['James Trafford', 'Goalkeeper', 'Manchester City'],
        ['John Stones', 'Defender', 'Manchester City'],
        ['Marc Guéhi', 'Defender', 'Manchester City'],
        ['Reece James', 'Defender', 'Chelsea'],
        ['Ezri Konsa', 'Defender', 'Aston Villa'],
        ['Dan Burn', 'Defender', 'Newcastle United'],
        ['Tino Livramento', 'Defender', 'Newcastle United'],
        ['Djed Spence', 'Defender', 'Tottenham Hotspur'],
        ['Nico O\'Reilly', 'Defender', 'Manchester City'],
        ['Jarell Quansah', 'Defender', 'Bayer Leverkusen'],
        ['Jordan Henderson', 'Midfielder', 'Brentford'],
        ['Declan Rice', 'Midfielder', 'Arsenal'],
        ['Jude Bellingham', 'Midfielder', 'Real Madrid'],
        ['Morgan Rogers', 'Midfielder', 'Aston Villa'],
        ['Kobbie Mainoo', 'Midfielder', 'Manchester United'],
        ['Elliot Anderson', 'Midfielder', 'Nottingham Forest'],
        ['Harry Kane', 'Forward', 'Bayern Munich'],
        ['Marcus Rashford', 'Forward', 'Barcelona'],
        ['Bukayo Saka', 'Forward', 'Arsenal'],
        ['Ollie Watkins', 'Forward', 'Aston Villa'],
        ['Anthony Gordon', 'Forward', 'Newcastle United'],
        ['Eberechi Eze', 'Forward', 'Arsenal'],
        ['Noni Madueke', 'Forward', 'Arsenal'],
        ['Ivan Toney', 'Forward', 'Al Ahli'],
    ]],
    'croatia' => ['country' => 'Croatia', 'players' => [
        ['Dominik Livaković', 'Goalkeeper', 'Dinamo Zagreb'],
        ['Dominik Kotarski', 'Goalkeeper', 'Copenhagen'],
        ['Ivor Pandur', 'Goalkeeper', 'Hull City'],
        ['Joško Gvardiol', 'Defender', 'Manchester City'],
        ['Duje Ćaleta-Car', 'Defender', 'Real Sociedad'],
        ['Josip Šutalo', 'Defender', 'Ajax'],
        ['Josip Stanišić', 'Defender', 'Bayern Munich'],
        ['Marin Pongračić', 'Defender', 'Fiorentina'],
        ['Martin Erlić', 'Defender', 'Midtjylland'],
        ['Luka Vušković', 'Defender', 'Hamburg'],
        ['Luka Modrić', 'Midfielder', 'AC Milan'],
        ['Mateo Kovačić', 'Midfielder', 'Manchester City'],
        ['Mario Pašalić', 'Midfielder', 'Atalanta'],
        ['Nikola Vlašić', 'Midfielder', 'Torino'],
        ['Luka Sučić', 'Midfielder', 'Real Sociedad'],
        ['Martin Baturina', 'Midfielder', 'Como'],
        ['Kristijan Jakić', 'Midfielder', 'Augsburg'],
        ['Petar Sučić', 'Midfielder', 'Inter Milan'],
        ['Nikola Moro', 'Midfielder', 'Bologna'],
        ['Toni Fruk', 'Midfielder', 'Rijeka'],
        ['Ivan Perišić', 'Forward', 'PSV Eindhoven'],
        ['Andrej Kramarić', 'Forward', 'Hoffenheim'],
        ['Ante Budimir', 'Forward', 'Osasuna'],
        ['Marco Pašalić', 'Forward', 'Orlando City'],
        ['Petar Musa', 'Forward', 'FC Dallas'],
        ['Igor Matanović', 'Forward', 'Freiburg'],
    ]],
];

$output = "<?php\n\n/**\n * World Cup 2026 player squads (code-maintained, not DB).\n */\nreturn [\n";

foreach ($squads as $key => $squad) {
    $output .= "    '{$key}' => [\n";
    $output .= "        'country' => ".var_export($squad['country'], true).",\n";
    $output .= "        'players' => [\n";
    foreach ($squad['players'] as $p) {
        $output .= '            ['
            ."'name' => ".var_export($p[0], true).', '
            ."'position' => ".var_export($p[1], true).', '
            ."'club' => ".var_export($p[2], true)."],\n";
    }
    $output .= "        ],\n";
    $output .= "    ],\n";
}

$output .= "];\n";

file_put_contents(__DIR__.'/../app/Data/world-cup-2026-players.php', $output);

$count = 0;
foreach ($squads as $squad) {
    $count += count($squad['players']);
}
echo "Generated {$count} players across ".count($squads)." squads.\n";
